### ISSUE TITLE
write MMTF

### ISSUE THREAD

**Issue by jamesmkrieger** [scipion-em/scipion-em-prody#65]
from Twitter/X (https://twitter.com/dawidzyla/status/1747076653371867216):
```
[Dawid Zyla](https://twitter.com/DawidZyla)
[@DawidZyla](https://twitter.com/DawidZyla)
Is there a way to easily convert pdb to mmtf in Python? I reached the 4th level of dependencies, and there is nothing else than frustration. Why is there nothing compatible in bioinformatics
```
```
[James Michael Krieger](https://twitter.com/james_krieger)
[@james_krieger](https://twitter.com/james_krieger)
We could probably add this to prody. We already have a connection to the mmtf parser
```

**Comment by Waris-95** [comment]
There are some Python libraries that can help you convert pdb to mmtf in Python, such as [atomium](https://pypi.org/project/atomium/), [mmtf-python](https://bioinformatics.stackexchange.com/questions/694/converter-between-pdb-or-mmcif-and-mmtf), and [Biopython](https://biopython.org/docs/dev/Tutorial/chapter_pdb.html). They can read and write pdb, cif, and mmtf files using different methods.

**Comment by jamesmkrieger** [comment]
Oh, I didn’t realise I had put this issue on this repo. We probably don’t need this functionality here specifically.

Thanks for the comment here too. Yes, writing a pdb with prody and reading with the libraries again could be an easier option actually, but I was hoping I could convert my ProDy objects internally. I’ll have a look at atomium too. Thanks!

**Comment by Waris-95** [comment]
I hoped everything worked out good!

**Comment by jamesmkrieger** [comment]
I think we still have a few issues. I will be sending a pull request to update BioPython and also checking why there are problems with reading the output with BioTite.

**Comment by Waris-95** [comment]
Right sounds good,

I'll be happy to help and debug. Might not be the senior/expert, but still. Would love to give it a shot!

**Comment by jamesmkrieger** [comment]
Thanks! Happy to have any help you can give.
